"""Autonomous Procurement Agent — identifies low stock, finds suppliers, creates POs."""

import logging
import json
from typing import List, Dict
from sqlalchemy.orm import Session

from app.models.product import Product
from app.models.supplier import Supplier
from app.models.tenant import Tenant
from app.services.procurement_service import (
    calculate_reorder_quantity,
    create_purchase_order,
    send_purchase_order_to_supplier,
    find_preferred_supplier,
    log_agent_audit,
)

logger = logging.getLogger(__name__)

AGENT_NAME = "procurement_agent"


def run_procurement_agent(
    db: Session,
    tenant_id: str,
    user_id: str,
    dry_run: bool = True,
) -> Dict:
    """
    Autonomous procurement agent that:
    1. Scans all products for reorder needs
    2. Finds preferred supplier
    3. Creates purchase orders
    4. Optionally sends to supplier
    """
    # Check feature flag
    tenant = db.query(Tenant).filter(Tenant.id == tenant_id).first()
    if not tenant:
        return {"error": "Tenant not found"}

    if not dry_run and not tenant.allow_auto_procurement:
        log_agent_audit(db, tenant_id, AGENT_NAME, "blocked",
                        output_data={"reason": "Auto-procurement disabled for tenant"}, status="blocked")
        return {"error": "Auto-procurement is disabled for this tenant", "mode": "blocked"}

    # 1. Analyze all products
    products = db.query(Product).filter(Product.tenant_id == tenant_id).all()
    analyses = [calculate_reorder_quantity(db, p) for p in products]
    needs_reorder = [a for a in analyses if a["needs_reorder"] and a["recommended_qty"] > 0]

    if not needs_reorder:
        log_agent_audit(db, tenant_id, AGENT_NAME, "scan",
                        output_data={"result": "No products need reorder"}, status="success")
        return {"mode": "dry_run" if dry_run else "autonomous", "actions": [], "message": "No products need reorder"}

    # 2. Find preferred supplier
    supplier = find_preferred_supplier(db, tenant_id)
    if not supplier:
        # Fall back to any supplier
        supplier = db.query(Supplier).filter(Supplier.tenant_id == tenant_id).first()

    if not supplier:
        log_agent_audit(db, tenant_id, AGENT_NAME, "no_supplier",
                        output_data={"result": "No supplier found"}, status="failed")
        return {"error": "No suppliers configured for tenant", "needs_reorder": needs_reorder}

    # 3. Build PO items
    items = []
    for analysis in needs_reorder:
        product = db.query(Product).filter(Product.id == analysis["product_id"]).first()
        if product:
            qty = max(analysis["recommended_qty"], supplier.minimum_order_quantity)
            items.append({
                "product_id": analysis["product_id"],
                "product_name": analysis["product_name"],
                "quantity": qty,
                "unit_cost": product.purchase_price if hasattr(product, 'purchase_price') and product.purchase_price else product.selling_price * 0.6,
            })

    action_log = {
        "mode": "dry_run" if dry_run else "autonomous",
        "supplier": {"id": str(supplier.id), "name": supplier.name},
        "items": items,
    }

    if dry_run:
        log_agent_audit(db, tenant_id, AGENT_NAME, "dry_run_analysis",
                        output_data=action_log, status="dry_run")
        return {**action_log, "message": "Dry run — no PO created. Review items above."}

    # 4. Create PO (autonomous mode)
    po = create_purchase_order(
        db=db,
        tenant_id=tenant_id,
        user_id=user_id,
        supplier_id=str(supplier.id),
        items=[{"product_id": i["product_id"], "quantity": i["quantity"], "unit_cost": i["unit_cost"]} for i in items],
        notes="Auto-generated by procurement agent",
        currency=supplier.currency,
    )

    # 5. Optionally send to supplier
    sent = send_purchase_order_to_supplier(db, po) if supplier.api_endpoint else False

    result = {
        **action_log,
        "po_id": str(po.id),
        "po_status": po.status.value if hasattr(po.status, 'value') else po.status,
        "sent_to_supplier": sent,
    }

    log_agent_audit(db, tenant_id, AGENT_NAME, "auto_po_created",
                    input_data={"needs_reorder_count": len(needs_reorder)},
                    output_data=result, status="success")

    return result
